export const ROUTES = {
    AUTH: {
        LOGIN: "/Kullanici/Giris",
        REGISTER: "/Kullanici/KayitOl",
        FORGOT_PASSWORD: "/Kullanici/SifremiUnuttum",
        RESET_PASSWORD: "/Kullanici/SifreyiSifirla",
        VERIFY_EMAIL: "/Kullanici/MailAktiflestir",
        TWO_FACTOR: "/Kullanici/2Faktor",
    },
    UI: {
        USER: "/Kullanici",
        LANDING: "/",
        USERS: "/Kullanicilar",
        NEW_USER: "/YeniKullanici",
        VIEW_USER: "/KullaniciGoruntule/:id",
        EDIT_USER: "/KullaniciDuzenle/:id",
        CLIENTS: "/Musteriler",
        NEW_CLIENT: "/YeniMusteri",
        VIEW_CLIENT: "/MusteriGoruntule/:id",
        EDIT_CLIENT: "/MusteriDuzenle/:id",
        MYCLIENTS: "/Musterilerim",
        SUBSTATION: "/Firmalar",
        NEW_SUBSTATION: "/YeniFirma",
        VIEW_SUBSTATION: "/FirmaGoruntule/:id",
        EDIT_SUBSTATION: "/FirmaDuzenle/:id",
        ACCOUNT_SETTINGS: "/HesapAyarlari",
    },
};
