### POST request to Substation API
POST http://localhost:8000/api/Substation
Content-Type: application/json

{
    "name": "John Doe"
}

###

GET http://localhost:8000/api/substation

###

GET http://localhost:8000/api/substation/1

###

PUT http://localhost:8000/api/substation/1
Content-Type: application/json

{
    "name": "Updated John Doe"
}

###

DELETE http://localhost:8000/api/substation/1

###